# Generated by Django 4.2.7 on 2025-07-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='verification_token',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
