# Generated by Django 4.2.7 on 2025-07-29 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_userprofile_email_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mobile_number',
        ),
    ]
