# Generated by Django 4.2.7 on 2025-08-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_defect_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='steps_to_reproduce',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('mentor', 'Mentor'), ('client', 'Client')], default='student', max_length=20),
        ),
    ]
