# Generated by Django 4.2.7 on 2025-08-05 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_defect_steps_to_reproduce_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='App.mentor'),
        ),
    ]
