# Generated by Django 4.2.7 on 2025-08-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_userprofile_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='project',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='App.project'),
        ),
    ]
