# Generated by Django 4.2.7 on 2025-08-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_remove_userprofile_project_userprofile_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='environment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
