# Generated by Django 4.2.7 on 2025-08-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_defect_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='application_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defect',
            name='defect_screenshots',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
