# Generated by Django 4.2.7 on 2025-08-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_defect_application_url_defect_defect_screenshots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='defect_screenshots',
            field=models.ImageField(blank=True, null=True, upload_to='defect_screenshots/'),
        ),
    ]
