# Generated by Django 4.2.7 on 2025-08-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_defect_defect_screenshots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defecthistory',
            name='changes',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
