# Generated by Django 4.2.7 on 2025-08-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_alter_defecthistory_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defecthistory',
            name='changes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
