# Generated by Django 4.2.7 on 2025-08-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_alter_defecthistory_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='mentor_state',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Invalid', 'Invalid')], default='Pending', max_length=20),
        ),
    ]
