# Generated by Django 4.2.7 on 2025-08-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_defect_mentor_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='severity',
            field=models.CharField(choices=[('S1', 'S1 - Blocker'), ('S2', 'S2 - Critical'), ('S3', 'S3 - Major'), ('S4', 'S4 - Minor')], default='S4', max_length=2),
        ),
        migrations.AlterField(
            model_name='defect',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('REOPEN', 'Reopen')], default='OPEN', max_length=40),
        ),
    ]
