# Generated by Django 4.2.7 on 2025-08-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_defect_severity_alter_defect_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='severity',
            field=models.CharField(choices=[('S1', 'S1 - Blocker'), ('S2', 'S2 - Critical'), ('S3', 'S3 - Major'), ('S4', 'S4 - Minor')], default='S4', max_length=10),
        ),
    ]
