# Generated by Django 4.2.7 on 2025-08-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_alter_defect_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='defect_video',
            field=models.FileField(blank=True, help_text='Optional video demonstrating the defect', null=True, upload_to='defect_videos/'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='severity',
            field=models.CharField(choices=[('S1', 'S1 - Blocker'), ('S2', 'S2 - Critical'), ('S3', 'S3 - Major'), ('S4', 'S4 - Minor'), ('S5', 'S5 - Medium')], default='S4', max_length=10),
        ),
    ]
