# Generated by Django 4.2.7 on 2025-08-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_defect_defect_video_alter_defect_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='severity',
            field=models.CharField(choices=[('S1', 'S1 - Blocker'), ('S2', 'S2 - Critical'), ('S3', 'S3 - Major'), ('S4', 'S4 - Minor'), ('S5', 'S5 - Medium'), ('S6', 'S6 - High')], default='S4', max_length=10),
        ),
    ]
