# Generated by Django 4.2.7 on 2025-08-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_alter_defect_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='defect_video',
            field=models.FileField(blank=True, null=True, upload_to='defect_videos/'),
        ),
    ]
