# Generated by Django 4.2.7 on 2025-08-28 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_alter_defect_defect_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defect',
            name='defect_screenshots',
        ),
        migrations.CreateModel(
            name='DefectScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='defect_screenshots/')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='App.defect')),
            ],
        ),
    ]
