# Generated by Django 4.2.7 on 2025-08-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_remove_defect_defect_screenshots_defectscreenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='defect_screenshots',
            field=models.ImageField(blank=True, null=True, upload_to='defect_screenshots/'),
        ),
        migrations.DeleteModel(
            name='DefectScreenshot',
        ),
    ]
