# Generated by Django 4.2.7 on 2025-08-28 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_defect_defect_screenshots_delete_defectscreenshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defect',
            name='defect_screenshots',
        ),
        migrations.AlterField(
            model_name='defect',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('REOPEN', 'Reopen'), ('APPROVED', 'Approved'), ('INVALID', 'Invalid'), ('PENDING', 'Pending')], default='OPEN', max_length=40),
        ),
        migrations.CreateModel(
            name='DefectScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='defect_screenshots/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='App.defect')),
            ],
        ),
    ]
